### ISSUE TITLE
部分手机上apache报错

### ISSUE THREAD

**Issue by YandZD** [volcengine/volc-sdk-java#11]
部分手机上apache报错，官方是不是要改用encodeHex呢

```
 java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.volcengine.helper.Utils.hashSHA256(Utils.java:45)
        at com.volcengine.auth.impl.SignerV4Impl.getSignRequest(SignerV4Impl.java:100)
        at com.volcengine.http.VolcengineInterceptor.intercept(VolcengineInterceptor.java:44)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.volcengine.service.BaseServiceImpl.makeRequest(BaseServiceImpl.java:274)
        at com.volcengine.service.BaseServiceImpl.post(BaseServiceImpl.java:261)
        at com.volcengine.service.visual.impl.VisualServiceImpl.poemMaterial(VisualServiceImpl.java:97)
        at com.desaysv.myapplication3.TestActivity.initClient(TestActivity.java:38)
        at com.desaysv.myapplication3.TestActivity.access$000(TestActivity.java:21)
        at com.desaysv.myapplication3.TestActivity$1.run(TestActivity.java:70)
```

**Comment by volc-sdk-team** [comment]
由于该 issue 已闲置较长时间，我们将暂时关闭。如果您仍有相关问题：
- 可以重新reopen issue 或者提交 issue
- 或通过[官网工单系统](https://console.volcengine.com/workorder/create)提交支持请求
我们会持续关注并及时响应您的需求。感谢您的理解！
